version: '3'
networks:
  selenoid:
    external:
      name: selenoid
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "/c/Users/Admin/selenoid:/etc/selenoid"
      - "//var/run/docker.sock:/var/run/docker.sock"
      - "/c/Users/Admin/selenoid/video:/opt/selenoid/video"
      - "/c/Users/Admin/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4445:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8084:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]